"""
Structured error responses with machine-readable codes.
"""
from enum import Enum
from pydantic import BaseModel
from typing import Any


class ErrorCode(str, Enum):
    # Auth
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS"

    # Agent
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_SUSPENDED = "AGENT_SUSPENDED"
    AGENT_PANIC = "AGENT_PANIC"

    # Policy
    POLICY_DENIED = "POLICY_DENIED"
    POLICY_ENGINE_ERROR = "POLICY_ENGINE_ERROR"

    # Wallet
    WALLET_INSUFFICIENT_FUNDS = "WALLET_INSUFFICIENT_FUNDS"
    WALLET_FROZEN = "WALLET_FROZEN"
    WALLET_DAILY_LIMIT = "WALLET_DAILY_LIMIT"
    WALLET_MONTHLY_LIMIT = "WALLET_MONTHLY_LIMIT"

    # Security
    PROMPT_INJECTION = "PROMPT_INJECTION"
    ANOMALY_DETECTED = "ANOMALY_DETECTED"
    CIRCUIT_BREAKER = "CIRCUIT_BREAKER"
    SSRF_BLOCKED = "SSRF_BLOCKED"

    # Proxy
    HITL_PENDING = "HITL_PENDING"
    NO_PERMISSION = "NO_PERMISSION"
    UPSTREAM_ERROR = "UPSTREAM_ERROR"
    UPSTREAM_TIMEOUT = "UPSTREAM_TIMEOUT"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"

    # Rate limit
    RATE_LIMITED = "RATE_LIMITED"

    # General
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    REQUEST_TOO_LARGE = "REQUEST_TOO_LARGE"


class ErrorDetail(BaseModel):
    code: str
    message: str
    details: Any = None